<div style="text-align: center;">
    <h1> Eliminasi Gaussian </h1>
</div>

$$
\begin{bmatrix}
a & b & c & \mid & d \\
e & f & g & \mid & h \\
i & j & k & \mid & l \\
\end{bmatrix}
\rightarrow
\begin{bmatrix}
1 & 0 & 0 & \mid & d \\
0 & 1 & 0 & \mid & h \\
0 & 0 & 1 & \mid & l \\
\end{bmatrix}
$$




Algoritma dari Eliminasi Gaussian diberikan sebagai berikut, yang mana penyelesaian suatu sistem persamaan linear dilakukan dengan mengubah *augmented matrix* (matrix sebelah kiri) menjadi matrix RROF *row-reduced echelon form* (matix sebelah kanan) sehingga nilai tiap variabel dapat ditentukan

Kita akan bekerja dengan Matriks Non-Singular untuk menyederhanakan masalah yang akan kita kerjakan sehingga tiap baris persamaan memiliki solusi yang unik. 

Metode yang digunakan untuk dapat mencapai matriks RROF ialah:

- **Pertukaran Baris Matriks:** Menyusun baris sehingga nilai konstanta pada diagonal utama tidaklah 0
- **Skala Baris Matriks:** Perkalian suatu baris dengan nilai skalar bukan 0
- **Perubahan Baris Matriks:**: Mengganti nilai seluruh baris matriks dengan penjumlahan terhadap dirinya sendiri dan baris lainnya


## Daftar Isi

Course Eliminasi Gaussian kali ini memiliki *difficulty curve* yang cukup tinggi daripada sebelumnya. Pastikan Anda telah menyelesaikan **Course Preliminaries NumpyIntroduction**

## Import Dependencies

In [3]:
import numpy as np

## Augmentasi Matrix

Diberikan sistem persamaan linear 
$$
\begin{align*}
2x_1 + 3x_2 + 5x_3&= 12 \\
-3x_1 - 2x_2 + 4x_3 &= -2 \\
x_1 + x_2 - 2x_3  &= 8 \\
\end{align*}
$$

Matrikx $([A | B])$ dideklarasikan dengan (A) menyatakan matriks koefisien (kiri) sementara (B) menyatakan matriks konstan (kanan)

$$A = \begin{bmatrix} \phantom-2&\phantom-3&\phantom-5 \\ -3&-2&\phantom-4 \\ \phantom-1&\phantom-1&-2 \end{bmatrix}$$

$$B = \begin{bmatrix} \phantom-12 \\ -2 \\ \phantom-8\end{bmatrix}$$

Dengan demikian 

$$([A | B]) = \begin{bmatrix}
\phantom{-}2 & \phantom{-}3 & \phantom{-}5 & | & \phantom{-}12 \\
-3 & -2 & \phantom-4 & | & -2 \\
\phantom{-}1 & \phantom{-}1 & -2 & | & \phantom{-}8 \\
\end{bmatrix}$$

Proses augmentasi ini dapat dicapai dengan menggunakan fungsi bawaan `numpy.hstack()`

In [4]:
def augmented_matrix(A,B):
    '''
    Menggabungkan matriks A,B secara horizontal

    Parameter
    - A -> (np.array) size nxn
    - B -> (np.array) size nx1

    Output:
    stacked -> np.array matriks teraugmentasi
    '''
    #Tulis Kode Anda di sini!
    stacked = np.hstack((A,B))
    #Berhenti
    return stacked

Mari kita mencoba fungsi di atas dengan matriks A dan matriks B sebagaimana yang telah disebutkan

`numpy.hstack()` umumnya digunakan untuk matrix 2D seperti yang kita pakai. Namun, dalam menggunakan fungsi ini terdapat hal-hal yang perlu diperhatikan:

1. Tiap matriks memerlukan dimensi yang sama
2. Jumlah baris dari tiap matriks perlu bernilai sama

In [48]:
A = np.array([[2,3,5],[-3,-2,4],[1,1,2]])
B = np.array([[12,-2,8]]).reshape(-1,1)
#Perhatikan bahwa matriks A dan B memiliki jumlah baris yang sama
print(f'''Dimensi Matriks A: {A.shape}
Dimensi Matriks B: {B.shape}''')
print(f'Hasil Augmentasi Matriks: \n{augmented_matrix(A,B)}')

Dimensi Matriks A: (3, 3)
Dimensi Matriks B: (3, 1)
Hasil Augmentasi Matriks: 
[[ 2  3  5 12]
 [-3 -2  4 -2]
 [ 1  1  2  8]]


## Pertukaran Baris Matrix

Perhatikan contoh matriks $M$ di bawah

$$
\begin{bmatrix}
\color{red}0 & \color{darkred}4 & \color{darkred}8 & \mid & \color{darkred}1 \\
6 & 8 & 6 & \mid & 4 \\
8 & 0 & 5 & \mid & 9 
\end{bmatrix}
\rightarrow ?
\begin{bmatrix}
1 & 0 & 0 & \mid & d \\
0 & 1 & 0 & \mid & h \\
0 & 0 & 1 & \mid & l \\
\end{bmatrix}
$$


Dikarenakan terdapat angka 0 pada diagonal utama matriks, matriks M tidak akan dapat mencapai matriks RROF di samping kanan. 

Maka dari itu, diperlukan penukaran dari baris $M[0]$ dengan baris $M[n]$ yang memenuhi syarat (indeks baris dengan nilai bukan nol). 
Sebagai contoh, kita akan menukar kolom $M[0]$ dengan kolom $M[1]$


$$
\begin{bmatrix}
6 & 8 & 6 & \mid & 4 \\
\color{red}0 & \color{darkred}4 & \color{darkred}8 & \mid & \color{darkred}1 \\
8 & 0 & 5 & \mid & 9 
\end{bmatrix}
\rightarrow 
\begin{bmatrix}
1 & 0 & 0 & \mid & d \\
0 & 1 & 0 & \mid & h \\
0 & 0 & 1 & \mid & l \\
\end{bmatrix}
$$


Matriks ini telah memenuhi persyaratan. Untuk mencapai kondisi di atas kita perlu mendeklarasikan dua fungsi:

- Fungsi Pertukaran Baris
- Fungsi Pencarian Indeks Baris Bukan Nol




### Fungsi Pertukaran Baris

In [51]:
def swap_rows(M, row1, row2):
    '''
    Menukar baris matriks row 1 <-> row2
    '''
    M = M.copy() #Copy supaya matriks tidak mengubah matriks original
    M[[row1,row2]] = M[[row2,row1]]
    return M

Mari kita mulai mencoba fungsi di atas

In [55]:
M = np.array([[0,4,8,1],[6,-8,6,4],[8,0,5,9]])
row1 = 0
row2 = 1
print(f'Matriks Awal:\n{M}')
print('---------------')
print(f'Matriks Akhir: \n{swap_rows(M,row1,row2)}')

Matriks Awal:
[[ 0  4  8  1]
 [ 6 -8  6  4]
 [ 8  0  5  9]]
---------------
Matriks Akhir: 
[[ 6 -8  6  4]
 [ 0  4  8  1]
 [ 8  0  5  9]]


### Fungsi Pencarian Indeks Baris Bukan Nol

In [69]:
def non_zero_column(M, column, row_start=0):
    '''
    Mendapatkan index dari suatu baris dengan nilai tidak nol pertama
    pada kolom yang ingin dicari.

    Parameter:
    -matrix (np.array)
    -column (int): index kolom yang ingin dicari
    -row_start (int): index baris pertama untuk memulai pencarian

    Output:
    int (index baris) atau False jika tidak ditemukan nilai tidak nol
    '''

    column_array = M[row_start:, column]
    for i, val in enumerate(column_array):
        #pengulangan untuk tiap nilai pada column_array
        if not np.isclose(val, 0, atol = 1e-5):
            #np.isclose untuk mencari nilai yang mendekati 0 dengan toleransi 1e-5
            index = i+row_start
            return index
    #return False jika tidak ditemukan nilai tidak nol
    return False

Mari kita mulai mencoba fungsi di atas

In [73]:
M = np.array([[0,4,8,1],[6,-8,6,4],[8,0,5,9]])
#Dikarenakan terdapat angka 0 pada M[0,0], kita akan mendeklarasikan
#column = 0 dan row_start = 0
column = 0
row_start = 0
print(f'Matriks Awal:\n{M}')
print(f'Indeks Baris Bukan Nol Pertama pada Kolom-{column} ialah {non_zero_column(M,0, row_start)}')

Matriks Awal:
[[ 0  4  8  1]
 [ 6 -8  6  4]
 [ 8  0  5  9]]
Indeks Baris Bukan Nol Pertama pada Kolom-0 ialah 1


Dengan menggabungkan fungsi `swap_rows()` dan `non_zero_column()`, kita bisa mengautomatisasi proses perubahan baris pivot

In [76]:
M = np.array([[0,5,9,1,0],[6,0,6,9,4],[8,3,0,2,9]])
num_rows = M.shape[0] #Banyaknya baris dari matriks M

print(f'Matriks Awal:\n{M}\n')

for row in range(num_rows): #Iterasi untuk tiap baris M untuk memastikan nilai pivot
    column = row #Pivot berada pada diagonal utama M[n,n]
    pivot_candidate = M[row, column] #Mendapatkan nilai dari pivot pada M[n,n]
    
    if np.isclose(pivot_candidate, 0): #Pastikan bahwa nilai pivot M[n,n] tidak bernilai 0
        #Jika nilai pivot M[n,n] bernilai 0...
        pivot_index = non_zero_column(M,column,row) #Cari indeks baris terdekat dengan nilai kolom bukan nol
        #Lakukan pertukaran baris
        M = swap_rows(M, row, pivot_index)
        
print(f'Matriks Akhir: \n{M}')

Matriks Awal:
[[0 5 9 1 0]
 [6 0 6 9 4]
 [8 3 0 2 9]]

Matriks Akhir: 
[[8 3 0 2 9]
 [0 5 9 1 0]
 [6 0 6 9 4]]
